### ISSUE TITLE
Question about the gh action steps, also thank you

### ISSUE THREAD

**Issue by allen-munsch** [pmbanugo/heroku-review-app-actions#12]
Thank you for posting this github action.

In regards to the app setup and pipeline coupling where the app is moved into the "review" stage. Is there any benefits to doing it in 2 stages? Would it be possible to combine the two steps using?

https://devcenter.heroku.com/articles/platform-api-reference#review-app-create

**Comment by allen-munsch** [comment]
ah, upon further reading it seems the 2 stage approach uses endpoints which explicitly document the usage and expectation of the `app.json` being present in the source tar

where as the `/review-apps` endpoint makes no mention if it also looks for the app.json

**Comment by pmbanugo** [comment]
Also, the review apps API is disabled by Heroku because of the security incident. I don't think they've enabled yet because none of their recent updates states that.

**Comment by allen-munsch** [comment]
@pmbanugo Yes. Thanks!
